# Generated by Django 2.0.13 on 2019-11-19 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coral', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastmedicalhistory',
            options={'verbose_name': 'Past Medical History'},
        ),
    ]
